print("bienvenido al programa, calculadora de gananacias para su empresa. ")
print("")
nombre1=input("ingrese su primer nombre: ",)
nombre2=input("ingrese su segundo nombre: ",)
apellido1=input("ingrese su primer apellido: ",)
apellido2=input("ingrese su segundo apellido: ",)
print("")
empresa=input("nombre de la empresa: ")
print("")
print("")
print ("Bienvenido al sistema ", nombre1, nombre2, apellido1, apellido2 )
print("")
print("")
print (" empresa:" + empresa)
print("")
print("")

gananciaEnero=int(input("ingrese las ganacias de Enero: "))
gananciaFebrero=int(input("ingrese las ganacias de Febrero: "))
gananciaMarzo=int(input("ingrese las ganacias de Marzo: "))
print("")

gananciasTotales = gananciaEnero + gananciaFebrero + gananciaMarzo
print("las ganacias fueron de $: ",gananciasTotales)
print("")
print("")
print("Gracias por utilizar nuestros servicios, lo esperamos pronto")
